services:
  - type: web
    name: event-ticket-system
    env: python
    buildCommand: bash build.sh
    startCommand: gunicorn run:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
